version: "3"
services:
  backend:
    container_name: iungo-backend
    restart: always
    build: backend/
    image: steevejoseph/iungo-backend
    ports:
      - "5000:5000"
    networks:
      - appnet
  frontend:
    container_name: iungo-frontend
    restart: always
    build: frontend/
    image: steevejoseph/iungo-frontend
    ports:
      - "80:8080"
    networks:
      - appnet
    links:
      - backend
    depends_on:
      - backend
networks:
  appnet:
    driver: bridge
